// src/api.ts

import { randomBytes } from "node:crypto";
import { fileURLToPath } from "node:url";
import { join, dirname } from "node:path";
import { CompiledContract } from "@midnight-ntwrk/compact-js";
import {
  deployContract,
  findDeployedContract,
  type FoundContract,
} from "@midnight-ntwrk/midnight-js-contracts";
import { levelPrivateStateProvider } from "@midnight-ntwrk/midnight-js-level-private-state-provider";
import { NodeZkConfigProvider } from "@midnight-ntwrk/midnight-js-node-zk-config-provider";
import { indexerPublicDataProvider } from "@midnight-ntwrk/midnight-js-indexer-public-data-provider";
import { httpClientProofProvider } from "@midnight-ntwrk/midnight-js-http-client-proof-provider";
import { setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import {
  type ScoreWalletProvider,
  type EnvironmentConfiguration,
} from "./wallet.js";
import * as Score from "../contracts/managed/score/contract/index.js";
import type { ProvableCircuits } from "../contracts/managed/score/contract/index.js";
import {
  type ScorePrivateState,
  createScorePrivateState,
  serializeScorePrivateState,
} from "./types.js";
import { witnesses } from "./witnesses.js";

// -------------------------------------------------------
// CONFIG
// setNetworkId must be called before any SDK interaction — each config
// class calls it in its constructor so the caller doesn't have to remember.
// The proof server always runs locally; ZK proof generation is private.
//
// Both classes implement EnvironmentConfiguration from @midnight-ntwrk/testkit-js,
// which is the interface expected by FluentWalletBuilder in wallet.ts.
// -------------------------------------------------------

// Local devnet — all services run on localhost via docker compose
// Start with: docker compose up -d (compose file is in the project root)
export class LocalConfig implements EnvironmentConfiguration {
  readonly walletNetworkId = "undeployed" as const;
  readonly networkId = "undeployed";
  readonly node = "http://localhost:9944";
  readonly nodeWS = "ws://localhost:9944";
  readonly indexer = "http://localhost:8088/api/v4/graphql";
  readonly indexerWS = "ws://localhost:8088/api/v4/graphql/ws";
  readonly proofServer = "http://localhost:6300";
  readonly faucet = undefined;

  constructor() {
    setNetworkId("undeployed");
  }
}

// Preprod testnet — public hosted endpoints, proof server still runs locally
export class PreprodConfig implements EnvironmentConfiguration {
  readonly walletNetworkId = "preprod" as const;
  readonly networkId = "preprod";
  readonly node = "https://rpc.preprod.midnight.network";
  readonly nodeWS = "wss://rpc.preprod.midnight.network";
  readonly indexer = "https://indexer.preprod.midnight.network/api/v4/graphql";
  readonly indexerWS =
    "wss://indexer.preprod.midnight.network/api/v4/graphql/ws";
  readonly proofServer = "http://localhost:6300";
  readonly faucet = undefined;

  constructor() {
    setNetworkId("preprod");
  }
}

// -------------------------------------------------------
// PRIVATE STATE ID
// Used as the storage key in levelPrivateStateProvider.
// -------------------------------------------------------

export const ScorePrivateStateId = "score" as const;

// -------------------------------------------------------
// COMPILED CONTRACT
// CompiledContract.make() combines the generated contract class with
// witness implementations and the path to the compiled ZK circuit keys on disk.
// Score.Contract is the class generated by `npm run compile-contract`.
// -------------------------------------------------------

const ZK_CONFIG_PATH = join(
  dirname(fileURLToPath(import.meta.url)),
  "../contracts/managed/score"
);

const scoreCompiledContract = CompiledContract.make(
  "score",
  Score.Contract
).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets(ZK_CONFIG_PATH)
);

// -------------------------------------------------------
// PROVIDERS
// Wires together all six midnight-js providers:
//   privateStateProvider — LevelDB storage for ScorePrivateState (local)
//   publicDataProvider   — reads on-chain ledger state via the indexer
//   zkConfigProvider     — loads compiled ZK circuit keys from disk
//   proofProvider        — sends private witness data to the local proof server
//   walletProvider       — signs transactions (provided by ScoreWalletProvider)
//   midnightProvider     — submits transactions to the Midnight node (same instance)
//
// ScoreWalletProvider implements both WalletProvider and MidnightProvider,
// so the same object is passed to both slots.
// -------------------------------------------------------

export function configureProviders(
  walletProvider: ScoreWalletProvider,
  config: EnvironmentConfiguration,
  walletAddress: string
) {
  const zkConfigProvider = new NodeZkConfigProvider<
    keyof ProvableCircuits<unknown>
  >(ZK_CONFIG_PATH);
  return {
    privateStateProvider: levelPrivateStateProvider<
      typeof ScorePrivateStateId,
      ScorePrivateState
    >({
      privateStateStoreName: "score-tracker",
      accountId: walletAddress,
      privateStoragePasswordProvider: () =>
        process.env.SCORE_STORAGE_PASSWORD ?? "ScoreTracker-Dev1!",
    }),
    publicDataProvider: indexerPublicDataProvider(
      config.indexer,
      config.indexerWS
    ),
    zkConfigProvider,
    proofProvider: httpClientProofProvider(
      config.proofServer,
      zkConfigProvider
    ),
    walletProvider,
    midnightProvider: walletProvider,
  };
}

export type ScoreProviders = Awaited<ReturnType<typeof configureProviders>>;

// -------------------------------------------------------
// DEPLOY
// Deploys the smart contract to the network.
// The constructor() circuit runs atomically at deployment — it calls both witnesses
// and writes the initial commitment on-chain.
// -------------------------------------------------------

export async function deployTracker(providers: ScoreProviders) {
  const secretKey = randomBytes(32);
  const initialPrivateState = createScorePrivateState(secretKey, 0n);

  const deployed = await deployContract(providers, {
    compiledContract: scoreCompiledContract,
    privateStateId: ScorePrivateStateId,
    initialPrivateState,
  });

  console.log(
    `Contract deployed at: ${deployed.deployTxData.public.contractAddress}`
  );
  // Never log deployed or initialPrivateState — they contain the secret key
  return deployed;
}

export type DeployedScoreContract = FoundContract<Score.Contract>;

// -------------------------------------------------------
// JOIN
// Reconnects to an existing smart contract at a known address.
// If no private state is stored locally for this address, `initialPrivateState`
// is used as the starting point — so pass the correct secretKey.
// -------------------------------------------------------

export async function joinTracker(
  providers: ScoreProviders,
  contractAddress: string,
  secretKey: Uint8Array
): Promise<DeployedScoreContract> {
  return findDeployedContract(providers, {
    contractAddress,
    compiledContract: scoreCompiledContract,
    privateStateId: ScorePrivateStateId,
    initialPrivateState: createScorePrivateState(secretKey, 0n),
  });
}

// -------------------------------------------------------
// INCREMENT
// Calls the circuit, then updates local private state to match.
// -------------------------------------------------------

export async function increment(
  contract: DeployedScoreContract,
  providers: ScoreProviders
): Promise<void> {
  const stateBefore = await providers.privateStateProvider.get(
    ScorePrivateStateId
  );
  if (!stateBefore)
    throw new Error("No private state found. Run deploy or join first.");

  // The circuit reads the current score through the localScore witness,
  // verifies it matches the on-chain commitment, then updates the commitment.
  await contract.callTx.increment();

  // The circuit does not write back to local storage — update it manually.
  const stateAfter: ScorePrivateState = {
    ...stateBefore,
    score: stateBefore.score + 1n,
  };
  await providers.privateStateProvider.set(ScorePrivateStateId, stateAfter);
  console.log(`Score: ${stateBefore.score} → ${stateAfter.score}`);
}

// -------------------------------------------------------
// DECREMENT
// Same pattern as increment, but guards against going below zero.
// -------------------------------------------------------

export async function decrement(
  contract: DeployedScoreContract,
  providers: ScoreProviders
): Promise<void> {
  const stateBefore = await providers.privateStateProvider.get(
    ScorePrivateStateId
  );
  if (!stateBefore) throw new Error("No private state found. Run deploy or join first");
  if (stateBefore.score === 0n) throw new Error("Score is already zero.");

  await contract.callTx.decrement();

  const stateAfter: ScorePrivateState = {
    ...stateBefore,
    score: stateBefore.score - 1n,
  };
  await providers.privateStateProvider.set(ScorePrivateStateId, stateAfter);
  console.log(`Score: ${stateBefore.score} → ${stateAfter.score}`);
}

// -------------------------------------------------------
// EXPORT BACKUP
// Serializes private state to a JSON string the user can save.
// Writes to disk rather than stdout — never print the secret key to the terminal.
// -------------------------------------------------------

export async function exportBackup(providers: ScoreProviders): Promise<string> {
  const state = await providers.privateStateProvider.get(ScorePrivateStateId);
  if (!state) throw new Error("Nothing to export.");
  return JSON.stringify(serializeScorePrivateState(state), null, 2);
}
